name: TwinSpark CI
on: [push]
jobs:

  types:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v3
    - name: render
      run: make deps render
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # https://github.com/marketplace/actions/setup-java-jdk#supported-distributions
        java-version: '19'
    - run: npm i -g google-closure-compiler
    - run: make adv

  tests:
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v3
    - name: render
      run: make deps render
    - uses: browser-actions/setup-chrome@v1
    - run: npm i
    - run: CHROMIUM_BIN=$(which chrome) ./headless-tests.js public

  build:
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v3
    - name: render
      run: make deps render
    - uses: actions/upload-pages-artifact@v1
      with:
        path: public

  deploy:
    needs: build
    runs-on: buildjet-2vcpu-ubuntu-2204
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
