name: TwinSpark tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: browser-actions/setup-chrome@v1
    - run: npm i
    - run: CHROMIUM_BIN=$(which chrome) ./headless-tests.js
  types:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # https://github.com/marketplace/actions/setup-java-jdk#supported-distributions
        java-version: '19'
    - run: npm i -g google-closure-compiler
    - run: make adv
